DROP TABLE users CASCADE;
DROP TABLE routine CASCADE;
DROP TABLE exercises CASCADE;
DROP TABLE posts CASCADE;
DROP TABLE comments CASCADE;
DROP TABLE posts_likes CASCADE;
DROP TABLE comments_likes CASCADE;
